#server:
#  port: 8085
#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/accounts


# Agregar su credenciales de mongo atlas
spring:
  data:
    mongodb:
      database: BootcampBank
      uri: mongodb+srv://jhianpol:12345@cluster0.hvzkv.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
server:
  port: 8085